[2024-03-27T19:09:22.994+0000] {processor.py:154} INFO - Started process (PID=34) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:09:23.001+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:09:23.002+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:09:23.002+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:09:23.027+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:09:23.025+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:09:23.028+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:09:23.051+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.059 seconds
[2024-03-27T19:09:53.124+0000] {processor.py:154} INFO - Started process (PID=84) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:09:53.127+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:09:53.127+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:09:53.127+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:09:53.150+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:09:53.148+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:09:53.151+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:09:53.169+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.050 seconds
[2024-03-27T19:10:23.351+0000] {processor.py:154} INFO - Started process (PID=151) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:10:23.354+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:10:23.357+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:10:23.356+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:10:23.380+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:10:23.378+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:10:23.382+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:10:23.401+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.058 seconds
[2024-03-27T19:10:38.497+0000] {processor.py:154} INFO - Started process (PID=34) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:10:38.499+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:10:38.500+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:10:38.500+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:10:38.539+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:10:38.537+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:10:38.539+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:10:38.583+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.089 seconds
[2024-03-27T19:11:11.932+0000] {processor.py:154} INFO - Started process (PID=84) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:11:11.933+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:11:11.934+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:11:11.934+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:11:11.956+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:11:11.951+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:11:11.956+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:11:11.982+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.055 seconds
[2024-03-27T19:11:43.564+0000] {processor.py:154} INFO - Started process (PID=141) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:11:43.568+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:11:43.570+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:11:43.570+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:11:43.605+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:11:43.603+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:11:43.606+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:11:43.684+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.123 seconds
[2024-03-27T19:12:18.976+0000] {processor.py:154} INFO - Started process (PID=43) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:12:18.978+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:12:18.979+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:12:18.979+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:12:19.032+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:12:19.029+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:12:19.033+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:12:19.178+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.204 seconds
[2024-03-27T19:12:49.515+0000] {processor.py:154} INFO - Started process (PID=93) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:12:49.519+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:12:49.521+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:12:49.521+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:12:49.604+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:12:49.586+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:12:49.610+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:12:49.684+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.184 seconds
[2024-03-27T19:13:24.739+0000] {processor.py:154} INFO - Started process (PID=153) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:13:24.743+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:13:24.747+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:13:24.746+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:13:24.990+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:13:24.969+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:13:24.993+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:13:25.117+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.433 seconds
[2024-03-27T19:13:55.613+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:13:55.615+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:13:55.615+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:13:55.615+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:13:55.627+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:13:55.626+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:13:55.627+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:13:55.655+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.044 seconds
[2024-03-27T19:14:26.275+0000] {processor.py:154} INFO - Started process (PID=92) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:14:26.276+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:14:26.277+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:14:26.277+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:14:26.301+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:14:26.299+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:14:26.302+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:14:26.328+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.056 seconds
[2024-03-27T19:14:57.025+0000] {processor.py:154} INFO - Started process (PID=152) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:14:57.031+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:14:57.034+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:14:57.034+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:14:57.071+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:14:57.062+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:14:57.072+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:14:57.138+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.119 seconds
[2024-03-27T19:15:20.143+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:15:20.145+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:15:20.146+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:15:20.146+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:15:20.162+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:15:20.161+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:15:20.163+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:15:20.179+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.040 seconds
[2024-03-27T19:15:50.717+0000] {processor.py:154} INFO - Started process (PID=101) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:15:50.727+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:15:50.734+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:15:50.734+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:15:50.833+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:15:50.823+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:15:50.834+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:15:51.071+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.373 seconds
[2024-03-27T19:16:21.188+0000] {processor.py:154} INFO - Started process (PID=159) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:16:21.196+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:16:21.198+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:16:21.198+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:16:21.284+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:16:21.279+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:16:21.286+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:16:21.392+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.214 seconds
[2024-03-27T19:16:49.164+0000] {processor.py:154} INFO - Started process (PID=41) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:16:49.165+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:16:49.166+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:16:49.166+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:16:49.190+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:16:49.188+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:16:49.190+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:16:49.209+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.052 seconds
[2024-03-27T19:17:20.170+0000] {processor.py:154} INFO - Started process (PID=99) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:17:20.192+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:17:20.193+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:17:20.193+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:17:20.376+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:17:20.352+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:17:20.380+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:17:22.884+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 2.730 seconds
[2024-03-27T19:18:18.543+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:18:18.547+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:18:18.548+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:18:18.548+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:18:18.567+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:18:18.566+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:18:18.568+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:18:18.592+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.053 seconds
[2024-03-27T19:18:49.082+0000] {processor.py:154} INFO - Started process (PID=100) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:18:49.085+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:18:49.085+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:18:49.085+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:18:49.111+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:18:49.109+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:18:49.111+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:18:49.128+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.049 seconds
[2024-03-27T19:19:19.751+0000] {processor.py:154} INFO - Started process (PID=160) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:19:19.756+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:19:19.837+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:19:19.775+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:19:39.996+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:19:39.997+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:19:39.998+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:19:39.998+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:19:40.018+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:19:40.017+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:19:40.018+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:19:40.032+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.037 seconds
[2024-03-27T19:20:14.994+0000] {processor.py:154} INFO - Started process (PID=101) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:20:15.003+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:20:15.018+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:20:15.018+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:20:15.406+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:20:15.362+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:20:15.437+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:20:19.285+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 4.321 seconds
[2024-03-27T19:21:22.422+0000] {processor.py:154} INFO - Started process (PID=41) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:21:22.424+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:21:22.425+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:21:22.425+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:21:22.437+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:21:22.436+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:21:22.437+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:21:22.449+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.030 seconds
[2024-03-27T19:21:53.147+0000] {processor.py:154} INFO - Started process (PID=91) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:21:53.148+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:21:53.149+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:21:53.149+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:21:53.161+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:21:53.160+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:21:53.161+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:21:53.172+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.027 seconds
[2024-03-27T19:22:24.055+0000] {processor.py:154} INFO - Started process (PID=151) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:22:24.088+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:22:24.108+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:22:24.104+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:22:29.715+0000] {processor.py:154} INFO - Started process (PID=32) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:22:29.716+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:22:29.717+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:22:29.717+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:22:29.732+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:22:29.730+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:22:29.732+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:22:29.747+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.035 seconds
[2024-03-27T19:23:00.469+0000] {processor.py:154} INFO - Started process (PID=100) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:23:00.471+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:23:00.471+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:23:00.471+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:23:00.487+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:23:00.486+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:23:00.488+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:23:00.499+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.033 seconds
[2024-03-27T19:24:26.414+0000] {processor.py:154} INFO - Started process (PID=159) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:24:26.416+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:24:26.417+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:24:26.417+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:24:26.445+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:24:26.444+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:24:26.446+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:24:26.475+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.067 seconds
[2024-03-27T19:24:53.092+0000] {processor.py:154} INFO - Started process (PID=32) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:24:53.093+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:24:53.094+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:24:53.094+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:24:53.110+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:24:53.109+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:24:53.111+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:24:53.121+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.032 seconds
[2024-03-27T19:25:23.501+0000] {processor.py:154} INFO - Started process (PID=99) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:25:23.503+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:25:23.503+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:25:23.503+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:25:23.527+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:25:23.525+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:25:23.527+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:25:23.541+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.045 seconds
[2024-03-27T19:25:53.630+0000] {processor.py:154} INFO - Started process (PID=168) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:25:53.631+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:25:53.632+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:25:53.632+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:25:53.648+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:25:53.646+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:25:53.648+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:25:53.670+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.043 seconds
[2024-03-27T19:26:24.327+0000] {processor.py:154} INFO - Started process (PID=227) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:26:24.330+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:26:24.332+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:26:24.332+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:26:24.354+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:26:24.352+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:26:24.354+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:26:24.373+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.052 seconds
[2024-03-27T19:26:26.468+0000] {processor.py:154} INFO - Started process (PID=277) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:26:26.469+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:26:26.469+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:26:26.469+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:26:26.480+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:26:26.479+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:26:26.480+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:26:26.493+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.027 seconds
[2024-03-27T19:26:56.187+0000] {processor.py:154} INFO - Started process (PID=34) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:26:56.188+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:26:56.188+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:26:56.188+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:26:56.198+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:26:56.197+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:26:56.198+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:26:56.209+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.024 seconds
[2024-03-27T19:27:15.119+0000] {processor.py:154} INFO - Started process (PID=93) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:27:15.122+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:27:15.123+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:27:15.123+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:27:15.147+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:27:15.145+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:27:15.147+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:27:15.162+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.048 seconds
[2024-03-27T19:27:45.471+0000] {processor.py:154} INFO - Started process (PID=155) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:27:45.473+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:27:45.474+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:27:45.474+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:27:45.496+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:27:45.495+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:27:45.497+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:27:45.511+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.046 seconds
[2024-03-27T19:28:33.335+0000] {processor.py:154} INFO - Started process (PID=259) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:28:33.338+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:28:33.342+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:28:33.341+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:28:33.371+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:28:33.367+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:28:33.371+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:28:33.407+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.080 seconds
[2024-03-27T19:29:06.753+0000] {processor.py:154} INFO - Started process (PID=308) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:29:06.756+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:29:06.757+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:29:06.757+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:29:06.801+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:29:06.786+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:29:06.802+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:29:06.827+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.076 seconds
[2024-03-27T19:29:37.372+0000] {processor.py:154} INFO - Started process (PID=363) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:29:37.373+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:29:37.373+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:29:37.373+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:29:37.387+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:29:37.385+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:29:37.388+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:29:37.410+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.041 seconds
[2024-03-27T19:30:09.493+0000] {processor.py:154} INFO - Started process (PID=402) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:30:09.495+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:30:09.496+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:30:09.496+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:30:09.521+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:30:09.513+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:30:09.525+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:30:09.574+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.083 seconds
[2024-03-27T19:30:25.020+0000] {processor.py:154} INFO - Started process (PID=430) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:30:25.021+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:30:25.022+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:30:25.022+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:30:25.087+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:30:25.081+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:30:25.087+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:30:25.146+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.142 seconds
[2024-03-27T19:30:56.207+0000] {processor.py:154} INFO - Started process (PID=479) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:30:56.208+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:30:56.208+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:30:56.208+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:30:56.220+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:30:56.219+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:30:56.220+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:30:56.241+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.036 seconds
[2024-03-27T19:31:26.275+0000] {processor.py:154} INFO - Started process (PID=530) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:31:26.275+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:31:26.276+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:31:26.276+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:31:26.286+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:31:26.285+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:31:26.286+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:31:26.297+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.024 seconds
[2024-03-27T19:32:01.581+0000] {processor.py:154} INFO - Started process (PID=551) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:32:01.584+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:32:01.585+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:32:01.585+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:32:01.611+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:32:01.609+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:32:01.613+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:32:01.634+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.058 seconds
[2024-03-27T19:32:44.919+0000] {processor.py:154} INFO - Started process (PID=597) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:32:44.925+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:32:44.927+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:32:44.927+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:32:45.018+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:32:45.013+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:32:45.019+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:32:45.096+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.187 seconds
[2024-03-27T19:33:18.108+0000] {processor.py:154} INFO - Started process (PID=658) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:33:18.113+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:33:18.119+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:33:18.117+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:33:18.182+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:33:18.176+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:33:18.183+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:33:18.248+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.156 seconds
[2024-03-27T19:33:48.459+0000] {processor.py:154} INFO - Started process (PID=717) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:33:48.468+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:33:48.470+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:33:48.470+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:33:48.532+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:33:48.523+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:33:48.535+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:33:48.605+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.166 seconds
[2024-03-27T19:34:19.473+0000] {processor.py:154} INFO - Started process (PID=770) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:34:19.477+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:34:19.483+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:34:19.483+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:34:19.565+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:34:19.556+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:34:19.567+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:34:19.638+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.187 seconds
[2024-03-27T19:34:32.254+0000] {processor.py:154} INFO - Started process (PID=787) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:34:32.258+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:34:32.258+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:34:32.258+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:34:32.276+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:34:32.273+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:34:32.278+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:34:32.299+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.048 seconds
[2024-03-27T19:35:04.041+0000] {processor.py:154} INFO - Started process (PID=841) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:35:04.044+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:35:04.047+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:35:04.047+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:35:04.090+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:35:04.085+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:35:04.092+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:35:04.156+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.126 seconds
[2024-03-27T19:35:36.819+0000] {processor.py:154} INFO - Started process (PID=894) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:35:36.822+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:35:36.832+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:35:36.832+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:35:36.951+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:35:36.941+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:35:36.951+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:35:37.051+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.274 seconds
[2024-03-27T19:36:11.141+0000] {processor.py:154} INFO - Started process (PID=914) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:36:11.146+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:36:11.148+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:36:11.148+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:36:11.235+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:36:11.228+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:36:11.240+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:36:11.424+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.337 seconds
[2024-03-27T19:36:47.464+0000] {processor.py:154} INFO - Started process (PID=34) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:36:47.466+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:36:47.469+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:36:47.468+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:36:47.536+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:36:47.534+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:36:47.537+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:36:47.571+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.120 seconds
[2024-03-27T19:37:15.472+0000] {processor.py:154} INFO - Started process (PID=82) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:37:15.474+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:37:15.475+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:37:15.475+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:37:15.514+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:37:15.507+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:37:15.514+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:37:15.538+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.070 seconds
[2024-03-27T19:37:40.856+0000] {processor.py:154} INFO - Started process (PID=104) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:37:40.858+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:37:40.859+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:37:40.859+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:37:40.918+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:37:40.910+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:37:40.920+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:37:41.183+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.340 seconds
[2024-03-27T19:37:54.501+0000] {processor.py:154} INFO - Started process (PID=34) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:37:54.503+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:37:54.504+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:37:54.504+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:37:54.524+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:37:54.521+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:37:54.525+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:37:54.540+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.041 seconds
[2024-03-27T19:38:29.816+0000] {processor.py:154} INFO - Started process (PID=83) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:38:29.817+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:38:29.817+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:38:29.817+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:38:29.835+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:38:29.834+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:38:29.837+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:38:29.852+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.041 seconds
[2024-03-27T19:39:49.654+0000] {processor.py:154} INFO - Started process (PID=52) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:39:49.658+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:39:49.660+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:39:49.659+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:39:49.720+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:39:49.714+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:39:49.723+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:39:49.781+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.135 seconds
[2024-03-27T19:40:22.893+0000] {processor.py:154} INFO - Started process (PID=108) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:40:22.902+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:40:22.910+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:40:22.910+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:40:23.178+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:40:23.133+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:40:23.211+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:40:24.233+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 1.355 seconds
[2024-03-27T19:40:58.665+0000] {processor.py:154} INFO - Started process (PID=160) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:40:58.677+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:40:58.682+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:40:58.679+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:40:58.776+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:40:58.767+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:40:58.777+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:40:58.872+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.228 seconds
[2024-03-27T19:41:38.398+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:41:38.399+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:41:38.400+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:41:38.400+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:41:38.415+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:41:38.414+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:41:38.415+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:41:38.431+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.036 seconds
[2024-03-27T19:42:09.247+0000] {processor.py:154} INFO - Started process (PID=92) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:42:09.249+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:42:09.251+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:42:09.251+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:42:09.285+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:42:09.281+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:42:09.285+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:42:09.321+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.081 seconds
[2024-03-27T19:42:45.248+0000] {processor.py:154} INFO - Started process (PID=142) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:42:45.253+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:42:45.258+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:42:45.258+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:42:45.357+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:42:45.354+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 13, in <module>
    catchup=False
TypeError: __init__() got an unexpected keyword argument 'task_id'
[2024-03-27T19:42:45.361+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:42:45.507+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.304 seconds
[2024-03-27T19:44:24.712+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:44:24.713+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:44:24.716+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:44:24.716+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:44:24.789+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:44:25.038+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:44:25.038+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:producer_test
[2024-03-27T19:44:25.056+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:44:25.056+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:producer_test
[2024-03-27T19:44:25.067+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:44:25.067+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:producer_test
[2024-03-27T19:44:25.068+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:44:25.067+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:44:25.093+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:44:25.093+0000] {dag.py:2606} INFO - Creating ORM DAG for producer_test
[2024-03-27T19:44:25.121+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:44:25.120+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-26T00:00:00+00:00, run_after=2024-03-27T00:00:00+00:00
[2024-03-27T19:44:25.154+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.450 seconds
[2024-03-27T19:44:55.360+0000] {processor.py:154} INFO - Started process (PID=92) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:44:55.365+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:44:55.369+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:44:55.369+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:44:55.586+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:45:17.875+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:45:17.874+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:45:17.924+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:45:17.924+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-26T00:00:00+00:00, run_after=2024-03-27T00:00:00+00:00
[2024-03-27T19:45:18.010+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 22.661 seconds
[2024-03-27T19:46:13.573+0000] {processor.py:154} INFO - Started process (PID=41) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:46:13.578+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:46:13.578+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:46:13.578+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:46:13.612+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:46:13.654+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:46:13.654+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:46:13.673+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:46:13.673+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-26T00:00:00+00:00, run_after=2024-03-27T00:00:00+00:00
[2024-03-27T19:46:13.697+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.127 seconds
[2024-03-27T19:46:44.063+0000] {processor.py:154} INFO - Started process (PID=95) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:46:44.064+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:46:44.064+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:46:44.064+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:46:44.088+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:46:44.116+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:46:44.116+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:46:44.132+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:46:44.131+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-27T00:00:00+00:00, run_after=2024-03-28T00:00:00+00:00
[2024-03-27T19:46:44.148+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.088 seconds
[2024-03-27T19:47:22.823+0000] {processor.py:154} INFO - Started process (PID=119) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:47:22.825+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:47:22.825+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:47:22.825+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:47:22.851+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:47:22.920+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:47:22.920+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:47:22.995+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:47:22.995+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-27T00:00:00+00:00, run_after=2024-03-28T00:00:00+00:00
[2024-03-27T19:47:23.066+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.246 seconds
[2024-03-27T19:47:45.881+0000] {processor.py:154} INFO - Started process (PID=41) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:47:45.882+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:47:45.883+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:47:45.883+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:47:45.900+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:47:45.938+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:47:45.938+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:47:45.965+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:47:45.965+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-27T00:00:00+00:00, run_after=2024-03-28T00:00:00+00:00
[2024-03-27T19:47:45.990+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.111 seconds
[2024-03-27T19:48:19.417+0000] {processor.py:154} INFO - Started process (PID=90) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:48:19.424+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:48:19.425+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:48:19.425+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:48:19.546+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:48:19.724+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:48:19.724+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:48:19.758+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:48:19.758+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-27T00:00:00+00:00, run_after=2024-03-28T00:00:00+00:00
[2024-03-27T19:48:19.796+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.411 seconds
[2024-03-27T19:48:49.954+0000] {processor.py:154} INFO - Started process (PID=149) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:48:49.957+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:48:49.957+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:48:49.957+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:48:50.013+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:48:50.118+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:48:50.118+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:48:50.164+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:48:50.161+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-27T00:00:00+00:00, run_after=2024-03-28T00:00:00+00:00
[2024-03-27T19:48:50.216+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.266 seconds
[2024-03-27T19:49:25.422+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:49:25.423+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:49:25.424+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:49:25.424+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:49:25.453+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:49:25.496+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:49:25.495+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:49:25.516+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:49:25.516+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-27T00:00:00+00:00, run_after=2024-03-28T00:00:00+00:00
[2024-03-27T19:49:25.542+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.124 seconds
[2024-03-27T19:49:58.045+0000] {processor.py:154} INFO - Started process (PID=92) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:49:58.049+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:49:58.051+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:49:58.051+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:49:58.217+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:49:58.366+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:49:58.365+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:49:58.483+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:49:58.479+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-27T00:00:00+00:00, run_after=2024-03-28T00:00:00+00:00
[2024-03-27T19:49:58.993+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.970 seconds
[2024-03-27T19:54:17.721+0000] {processor.py:154} INFO - Started process (PID=34) to work on /opt/airflow/dags/producer.py
[2024-03-27T19:54:17.723+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2024-03-27T19:54:17.724+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:54:17.724+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2024-03-27T19:54:17.762+0000] {processor.py:766} INFO - DAG(s) dict_keys(['producer_test']) retrieved from /opt/airflow/dags/producer.py
[2024-03-27T19:54:17.820+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:54:17.820+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2024-03-27T19:54:17.858+0000] {logging_mixin.py:120} INFO - [2024-03-27T19:54:17.858+0000] {dag.py:3340} INFO - Setting next_dagrun for producer_test to 2024-03-27T00:00:00+00:00, run_after=2024-03-28T00:00:00+00:00
[2024-03-27T19:54:17.886+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/producer.py took 0.168 seconds
